#!/bin/bash

source "$(dirname "$0")/constants"

MESSAGE="$(cat $1)"

if ! [[ $MESSAGE =~ $REQUIRED_COMMIT_PATTERN ]];
then
  echo "-"
  echo "The commit message must have the following format: [TEST-{number}] Implementation message"
  echo "-"
  echo "Your commit message was:"
  echo $MESSAGE
  echo "-"
  exit 1
fi
