#!/bin/bash

message="$(cat $1)"
requiredPattern="^\[TEST-[0-9]+\] .*$"

if ! [[ $message =~ $requiredPattern ]];
then
  echo "-"
  echo "The commit message must have this format: [TEST-{number}]"
  echo "Example: [TEST-264] New formula implemented"
  echo "-"
  echo "Your commit message was:"
  echo $message
  echo "-"
  exit 1
fi
