#!/bin/bash

# Get the current branch name
BRANCH_NAME="$(git symbolic-ref --short HEAD)"

# Extract TEST-<number> pattern from the branch name, if exists
BRANCH_ID="$(echo "$BRANCH_NAME" | sed -n 's/.*\(TEST-[0-9]\+\).*/[\1]/p')"

# Check if the branch is one of the allowed types (e.g. feature/ or bugfix/)
BRANCH_TYPE="$(echo "$BRANCH_NAME" | cut -d '/' -f 1)"

# Default branches to skip (excluded branches)
BRANCHES_TO_SKIP=("master" "preproduction")

# Default allowed branch types
ALLOWED_BRANCHES=("epic" "feature" "bugfix" "hotfix")

# Required commit pattern
REQUIRED_COMMIT_PATTERN="^\[TEST-[0-9]+\] .*$"
