#!/bin/bash

source "$(dirname "$0")/constants"

# Function to check if the branch is in a list
is_branch_in_list() {
  local branch="$1"
  local branch_list=("${@:2}")
  
  for b in "${branch_list[@]}"; do
    if [[ "$branch" == "$b" ]]; then
      return 0  # Found in the list
    fi
  done
  
  return 1  # Not found in the list
}

# Check if the branch is in the excluded list
if is_branch_in_list "$BRANCH_NAME" "${BRANCHES_TO_SKIP[@]}"; then
  echo "-"
  echo "No commits are allowed on excluded branch: $BRANCH_NAME"
  echo "-"
  exit 0
fi

if ! is_branch_in_list "$BRANCH_TYPE" "${ALLOWED_BRANCHES[@]}"; then
  echo "Invalid branch type: $BRANCH_TYPE. Must be one of: ${ALLOWED_BRANCHES[*]}"
  exit 0
fi

npm run test
