#!/bin/bash

source "$(dirname "$0")/constants"
source "$(dirname "$0")/functions"

protected_branch='master'

# Check if the branch is in the excluded list
if is_branch_in_list "$BRANCH_NAME" "${BRANCHES_TO_SKIP[@]}"; then
  echo "-"
  echo "Push is not allowed on excluded branch: $BRANCH_NAME"
  echo "-"
  exit 1
fi
