#!/bin/bash

source "$(dirname "$0")/constants"
source "$(dirname "$0")/functions"

# Check if the branch is in the excluded list
if is_branch_in_list "$BRANCH_NAME" "${BRANCHES_TO_SKIP[@]}"; then
  echo "-"
  echo "No commits are allowed on excluded branch: $BRANCH_NAME"
  echo "-"
  exit 0
fi

if ! is_branch_in_list "$BRANCH_TYPE" "${ALLOWED_BRANCHES[@]}"; then
  echo "Invalid branch type: $BRANCH_TYPE. Must be one of: ${ALLOWED_BRANCHES[*]}"
  exit 0
fi

npm run test
